### ISSUE TITLE
App / create layout - Calendar, Explore, Playlist

### ISSUE THREAD

**Issue by earlyoonj** [earlyoonj/plan-player#1]
# Requirement

# Todo
### Calendar
- Nav
    - [x] year, month picker → days

### Todos
- Nav
    - [x] nav picker → layout
- Explore
    - [x] Search
    - Groups 
        - [x] Artist
        - [x] Album
    - Tracks
        - [x] Filter
        - [x] Form
        - [x] Item
- _Statistics (later)_
- _Table (later)_
### Lists
- Nav
    - [x] nav radio → layout
- Playlists
    - [x] Form
    - [x] Playlist
 - _Schedule (later)_
### _Player (later)_
